/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddNode: typeof import('./src/components/AddNode.vue')['default']
    AduitNode: typeof import('./src/components/aduitNode.vue')['default']
    AuditNode: typeof import('./src/components/AuditNode.vue')['default']
    BaseNode: typeof import('./src/components/BaseNode.vue')['default']
    BranchNode: typeof import('./src/components/BranchNode.vue')['default']
    copy: typeof import('./src/components/AuditNode copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    EndNode: typeof import('./src/components/EndNode.vue')['default']
    IEpArrowRight: typeof import('~icons/ep/arrow-right')['default']
    IEpAvatar: typeof import('~icons/ep/avatar')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WriteNode: typeof import('./src/components/WriteNode.vue')['default']
  }
}
